# Problem 1 - Traveling Salesperson

In [1]:
import mlrose
import numpy as np
import pandas as pd
from sklearn import metrics
from matplotlib import pyplot as plt
%matplotlib inline

##OPTION 1, Coordinates
# Create list of city coordinates
coords_list = [(1, 1), (4, 2), (5, 2), (6, 4), (4, 4), (3, 6), (1, 5), (2, 3),(11, 11), (14, 12), (15, 12), (16, 14), (14, 14), (13, 16), (11, 15), (12, 13)]

# Initialize fitness function object using coords_list
fitness_coords = mlrose.TravellingSales(coords = coords_list)

#Define optimization problem object
problem_fit_coord = mlrose.TSPOpt(length = len(coords_list), coords = coords_list, maximize=False)
print(len(coords_list))

/home/kellgon/.local/lib/python3.6/site-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)


16


# Genetic

In [ ]:
# define the parameter values that should be searched
pop_size=200
mutation_prob= 0.1


best_state, best_fitness = mlrose.genetic_alg(problem_fit_coord, mutation_prob = mutation_prob, pop_size=pop_size,
                                              max_attempts = 1000, random_state = 3)
print("Mutation = ", mutation_prob)
print(best_state)
print(best_fitness)

#################
mutation_prob= 0.2

best_state, best_fitness = mlrose.genetic_alg(problem_fit_coord, mutation_prob = mutation_prob, pop_size=pop_size,
                                              max_attempts = 1000, random_state = 3)
print("Mutation = ", mutation_prob)
print(best_state)
print(best_fitness)

#################
mutation_prob= 0.3

best_state, best_fitness = mlrose.genetic_alg(problem_fit_coord, mutation_prob = mutation_prob, pop_size=pop_size,
                                              max_attempts = 1000, random_state = 3)
print("Mutation = ", mutation_prob)
print(best_state)
print(best_fitness)

#################
mutation_prob= 0.4

best_state, best_fitness = mlrose.genetic_alg(problem_fit_coord, mutation_prob = mutation_prob, pop_size=pop_size,
                                              max_attempts = 1000, random_state = 3)
print("Mutation = ", mutation_prob)
print(best_state)
print(best_fitness)

Mutation =  0.1
[14 15 12  8  3  6  5  2  1  4  0  7 10 11  9 13]
65.83809102607805
Mutation =  0.2
[ 8  3  4  0  1  2  7  5  6 13 14  9 11 12 10 15]
62.78823691279976
Mutation =  0.3
[ 4  3  2  1  0  7  6  5 13 12 14  8 10  9 11 15]
62.763263786340474


In [ ]:
plt.style.use('seaborn')
plt.plot(train_sizes, train_scores_mean, label='Training error')


plt.ylabel('Accuracy', fontsize=14)
plt.xlabel('Training set size', fontsize = 14)
plt.title('Learning Curves for KNN', fontsize=18, y=1.03)
plt.legend()

# Random Hill

In [ ]:
# Solve problem using the random hill climb
best_state, best_fitness = mlrose.random_hill_climb(problem_fit_coord,
                                              max_attempts = 2000, random_state = 3)

print(best_state)
print(best_fitness)

# Simulated Annealing

In [31]:
# Solve problem using simulated annealing

# Define decay schedule
schedule = mlrose.GeomDecay()


best_state, best_fitness = mlrose.simulated_annealing(problem_fit_coord, schedule=schedule,
                                              max_attempts = 1000, random_state = 3)

print("Simulated annealing with GeomDecay")
print(best_state)
print(best_fitness)

################
schedule = mlrose.ArithDecay()
best_state, best_fitness = mlrose.simulated_annealing(problem_fit_coord, schedule=schedule,
                                              max_attempts = 1000, random_state = 3)

print("Simulated annealing with ArithDecay")
print(best_state)
print(best_fitness)

################
schedule = mlrose.ExpDecay()
best_state, best_fitness = mlrose.simulated_annealing(problem_fit_coord, schedule=schedule,
                                              max_attempts = 1000, random_state = 3)

print("Simulated annealing with ExpDecay")
print(best_state)
print(best_fitness)

Simulated annealing with GeomDecay
[ 2  1  4  7  0  6  5 14 13 12 11 10  9 15  8  3]
50.76853164333302
Simulated annealing with ArithDecay
[ 5  6  7  0  1  2  4  3  8 15  9 10 11 12 13 14]
49.930809303501405


/home/kellgon/.local/lib/python3.6/site-packages/mlrose/algorithms.py:311: RuntimeWarning: overflow encountered in exp
  prob = np.exp(delta_e/temp)


Simulated annealing with ExpDecay
[ 1  4  7  0  6  5 15 14 13 12 11 10  9  8  3  2]
51.054900998200694


# MIMIC

In [ ]:
# Solve problem using mimic
pop_size=200 #(300 was 71 and 100 was 74)
max_attempts=100
keep_pct=0.1 

best_state, best_fitness = mlrose.mimic(problem_fit_coord, pop_size=pop_size, keep_pct=keep_pct,
                                              max_attempts = max_attempts, random_state = 3)
print("MIMIC with Keep_PCT of ", keep_pct)
print(best_state)
print(best_fitness)

################
keep_pct=0.2 

best_state, best_fitness = mlrose.mimic(problem_fit_coord, pop_size=pop_size, keep_pct=keep_pct,
                                              max_attempts = max_attempts, random_state = 3)
print("MIMIC with Keep_PCT of ", keep_pct)
print(best_state)
print(best_fitness)

######################
keep_pct=0.3 

best_state, best_fitness = mlrose.mimic(problem_fit_coord, pop_size=pop_size, keep_pct=keep_pct,
                                              max_attempts = max_attempts, random_state = 3)
print("MIMIC with Keep_PCT of ", keep_pct)
print(best_state)
print(best_fitness)

################
keep_pct=0.4 

best_state, best_fitness = mlrose.mimic(problem_fit_coord, pop_size=pop_size, keep_pct=keep_pct,
                                              max_attempts = max_attempts, random_state = 3)
print("MIMIC with Keep_PCT of ", keep_pct)
print(best_state)
print(best_fitness)

In [ ]:
plt.style.use('seaborn')
plt.plot(train_sizes, train_scores_mean, label='Training error')
plt.plot(train_sizes, validation_scores_mean, label='Validation error')

plt.ylabel('Accuracy', fontsize=14)
plt.xlabel('Training set size', fontsize = 14)
plt.title('Learning Curves for KNN', fontsize=18, y=1.03)
plt.legend()